In [11]:
from math import sin, cos, log, ceil
import numpy

# model parameters:
g = 9.81     # gravity in m s^{-2}
v_t = 30.0   # trim velocity in m s^{-1}
C_D = 1./40.  # drag coefficient --- or D/L if C_L=1
C_L = 1.   # for convenience, use C_L = 1

### set initial conditions ###
v0 = v_t     # start at the trim velocity (or add a delta)
theta0 = 0. # initial angle of trajectory
x0 = 0.     # horizontal position is arbitrary
y0 = 1000.  # initial altitude

def f(u):
    """Returns the right-hand side of the phugoid system of equations.

    Parameters
    ----------
    u : array of float
        array containing the solution at time n.

    Returns
    -------
    dudt : array of float
        array containing the RHS given u.
    """

    v = u[0]
    theta = u[1]
    x = u[2]
    y = u[3]
    return numpy.array([-g*sin(theta) - C_D/C_L*g/v_t**2*v**2,
                      -g*cos(theta)/v + g/v_t**2*v,
                      v*cos(theta),
                      v*sin(theta)])

def euler_step(u, f, dt):
    return u + dt * f(u)

T = 100                          # final time
dt = 0.001                         # time increment
N = int(T/dt)                    # number of time-steps
t = numpy.linspace(0, T, N)      # time discretization

# initialize the array containing the solution for each time-step
u = numpy.empty((N, 4))
u[0] = numpy.array([v0, theta0, x0, y0])# fill 1st element with initial values

# time loop - Euler method
# n cycles from 0 to N-2 included
for n in range(N-1):
    u[n+1] = euler_step(u[n], f, dt)

print (u[:])


[[ 3.00000000e+01  0.00000000e+00  0.00000000e+00  1.00000000e+03]
 [ 2.99997548e+01  0.00000000e+00  3.00000000e-02  1.00000000e+03]
 [ 2.99995095e+01 -5.34647185e-09  5.99997548e-02  1.00000000e+03]
 ...
 [ 2.98725185e+01 -2.95966328e-02  2.99698841e+03  9.25514604e+02]
 [ 2.98725656e+01 -2.95992740e-02  2.99701827e+03  9.25513720e+02]
 [ 2.98726128e+01 -2.96019142e-02  2.99704813e+03  9.25512836e+02]]
