In [ ]:
from math import sin, cos, log, ceil
import numpy

# model parameters:
g = 9.81     # gravity in m s^{-2}
v_t = 30.0   # trim velocity in m s^{-1}
C_D = 1./40.  # drag coefficient --- or D/L if C_L=1
C_L = 1.   # for convenience, use C_L = 1

### set initial conditions ###
v0 = v_t     # start at the trim velocity (or add a delta)
theta0 = 0. # initial angle of trajectory
x0 = 0.     # horizontal position is arbitrary
y0 = 1000.  # initial altitude

In [ ]:
def f(u):
    """Returns the right-hand side of the phugoid system of equations.

    Parameters
    ----------
    u : array of float
        array containing the solution at time n.

    Returns
    -------
    dudt : array of float
        array containing the RHS given u.
    """

    v = u[0]
    theta = u[1]
    x = u[2]
    y = u[3]
    return numpy.array([-g*sin(theta) - C_D/C_L*g/v_t**2*v**2,
                      -g*cos(theta)/v + g/v_t**2*v,
                      v*cos(theta),
                      v*sin(theta)])

In [ ]:
def euler_step(u, f, dt):
    return u + dt * f(u)

In [ ]:
T = 100                          # final time
dt = 0.1                         # time increment
N = int(T/dt)                    # number of time-steps
t = numpy.linspace(0, T, N)      # time discretization

# initialize the array containing the solution for each time-step
u = numpy.empty((N, 4))
u[0] = numpy.array([v0, theta0, x0, y0])# fill 1st element with initial values

# time loop - Euler method
# n cycles from 0 to N-2 included
for n in range(N-1):
    u[n+1] = euler_step(u[n], f, dt)

In [ ]:
print (u)


[[ 3.00000000e+01  0.00000000e+00  0.00000000e+00  1.00000000e+03]
 [ 2.99754750e+01  0.00000000e+00  3.00000000e+00  1.00000000e+03]
 [ 2.99509901e+01 -5.34863715e-05  5.99754750e+00  1.00000000e+03]
 ...
 [ 2.96104395e+01 -3.63254271e-02  2.98758370e+03  9.26549826e+02]
 [ 2.96221747e+01 -3.71583995e-02  2.99054279e+03  9.26442289e+02]
 [ 2.96347076e+01 -3.79644510e-02  2.99350297e+03  9.26332243e+02]]
